version: '3.8'

services:
  product-postgres:
    image: postgres
    container_name: product-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: productDb
    ports:
      - "5432:5432"
    volumes:
      - product-volume:/var/lib/postgresql/data
volumes:
  product-volume: